id: getting_started
namespace: zoomcamp

inputs:
  - id: name
    type: STRING
    default: Will

variables:
  welcome_message: "Hello, {{ inputs.name }}!"
  
tasks:
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: "{{ render(vars.welcome_message) }}"

  - id: goodbye_message
    type: io.kestra.plugin.core.log.Log
    message: "Goodbye, {{ inputs.name }}!"

pluginDefaults:
  io.kestra.plugin.core.log.Log:
    defaultLevel: ERROR

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 * * *"
    inputs:
      name: Sarah
