name: 'taxi_rides_ny'
version: '1.0.0'
config-version: 2

profile: 'taxi_rides_ny'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  taxi_rides_ny:
    staging:
      +materialized: view

    intermediate:
      +materialized: table

    marts:
      +materialized: table

vars:
  record_limit: 100000