services:
  pgdatabase:
    image: postgres:13
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"

volumes:
  ny_taxi_postgres_data:
    name: ny_taxi_postgres_data
  data_pgadmin:
    name: data_pgadmin
