taxi_rides_ny:
  target: dev
  outputs:
    dev:
      type: bigquery
      # method: oauth allows using 'gcloud auth application-default login'
      method: "{{ env_var('GCP_AUTH_METHOD', 'oauth') }}"
      project: "{{ env_var('GCP_PROJECT_ID', 'your-project-id') }}"
      dataset: "{{ env_var('GCP_DATASET', 'dbt_dev') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_KEYFILE_PATH', '/home/vscode/homework/gcp_key.json') }}"
      location: "{{ env_var('GCP_LOCATION', 'US') }}"
    
    prod:
      type: bigquery
      method: "{{ env_var('GCP_AUTH_METHOD', 'oauth') }}"
      project: "{{ env_var('GCP_PROJECT_ID', 'your-project-id') }}"
      dataset: "{{ env_var('GCP_DATASET_PROD', 'dbt_prod') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_KEYFILE_PATH', '/home/vscode/homework/gcp_key.json') }}"
      location: "{{ env_var('GCP_LOCATION', 'US') }}"